version: "3"

networks:
  my_network:
    driver: bridge

services:
  mysql:
    image: mysql
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - my_network
